### ISSUE TITLE
Bug when sorting an enumerable that includes nil

### ISSUE THREAD

**Issue by perlun** [jlindsey/semantic#13]
This is what I get:

```
rake aborted!
TypeError: can't dup NilClass
/Library/Ruby/Gems/2.0.0/gems/semantic-1.4.1/lib/semantic/version.rb:52:in `dup'
/Library/Ruby/Gems/2.0.0/gems/semantic-1.4.1/lib/semantic/version.rb:52:in `<=>'
/Users/plundberg/git/mforms-addons-platform/Rakefile:25:in `sort'
```

Too lazy to make a failing spec for it at the moment, but it should be trivial. IMHO, comparing "anything" to nil should always return 1, i.e. "anything" is higher than nil.

**Comment by jlindsey** [comment]
Hey @perlun I know this is a million years late but is this still an issue? If so could I bother you for an example?

**Comment by vmeyet** [comment]
This is still an issue:

```ruby
nil == Semantic::Version.new('1.0.0')
# false

Semantic::Version.new('1.0.0') == nil
# TypeError: can't dup NilClass

Semantic::Version.new('1.0.0') > nil
# TypeError: can't dup NilClass
```

Caused by the spaceship (`<=>`) operator not handling nil case

**Comment by jlindsey** [comment]
Thanks for the update @vmeyet. I'll take a look at this today and hopefully cut a new version with the fix.
